### ISSUE TITLE
Prevent re-renders of components on reconnect (also, fix flicker)

### ISSUE THREAD

**Issue by JulianKingman** [DesignmanIO/react-native-meteor-redux#3]
Currently when connectivity is restored, all components depending on the data are removed and restored, causing a flicker. We need to make it a little smarter so that data is merged, not completely replaced.

**Comment by UADACID** [comment]
hi, is this ready for production???

**Comment by JulianKingman** [comment]
Yes*
It's under active development, so make sure to check for updates if you run into problems, and submit issues.

I fixed these specific problems by directly connecting to minimongo.

**Comment by v3yr0n** [comment]
@JulianKingman this is still happening to me, using createContainer...
